### ISSUE TITLE
Remove broken package

### ISSUE THREAD

**Issue by joaander** [conda-forge/gsd-feedstock#21]
Hi @conda-forge/core,

Please move my package from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
because:

I accidentally built a package for python2.7 that does not support python 2.7.

The following files are broken:
- `osx-64/gsd-1.8.0-py27heacc8b8_0.tar.bz2`
- `linux-64/gsd-1.8.0-py27hc1659b7_0.tar.bz2`

**Comment by jjhelmus** [comment]
I moved the two packages to the `broken` label.  Can you confirm that everything is correct on anaconda.org now?

**Comment by joaander** [comment]
confirmed. Thanks!
